// src/components/Form.vue
<template lang='pug'>
div(data-set='nova-ferramenta')
  input(
    data-input='title',
    :value='ferramenta.title',
    @change='changeTitle($event)'
  )
  input(
    data-input='link',
    :value='ferramenta.link',
    @change='changeLink($event)'
  )
  input(
    data-input='description',
    :value='ferramenta.description',
    @change='changeDescription($event)'
  )
  input(
    data-input='marcadores',
    :value='ferramenta.marcadores',
    @change='changeMarcadores($event)'
  )
  button(action-trigger='adicionar', @click='adicionar') Adicionar
</template>

<script>
export default {
  props: ['tool'],
  created () {
    this.ferramenta = this.tool
  },
  data () {
    return {
      ferramenta: {}
    }
  },
  methods: {
    changeMarcadores (event) {
      this.ferramenta.marcadores = event.target.value
    },
    changeDescription (event) {
      this.ferramenta.description = event.target.value
    },
    changeLink (event) {
      this.ferramenta.link = event.target.value
    },
    changeTitle (event) {
      this.ferramenta.title = event.target.value
    },
    adicionar () {
      this.$emit('confirmar', this.ferramenta)
    }
  }
}
</script>

// app/react/src/components/Form.js
import React from 'react'

export default class Form extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
      tool: {
        title: '',
        link: '',
        description: '',
        marcadores: ''
      }
    }
  }

  onTitleKeyUp = (e) => {
    const before = this.state.tool
    const title = e.target.value
    const tool = { ...before, title }
    this.setState({ tool })
  }

  onLinkKeyUp = (e) => {
    const before = this.state.tool
    const link = e.target.value
    const tool = { ...before, link }
    this.setState({ tool })
  }

  onDescriptionKeyUp = (e) => {
    const before = this.state.tool
    const description = e.target.value
    const tool = { ...before, description }
    this.setState({ tool })
  }

  onMarcadoresKeyUp = (e) => {
    const before = this.state.tool
    const marcadores = e.target.value
    const tool = { ...before, marcadores }
    this.setState({ tool })
  }

  onAdicionarClick = () => {
    this.props.onAdicionar(this.state.tool)
  }

  render () {
    return(
      this.props.show &&
      <div>
        <input
          type='text'
          data-input='title'
          onKeyUp={this.onTitleKeyUp}
        />
        <input
          type='text'
          data-input='link'
          onKeyUp={this.onLinkKeyUp}
        />
        <input
          type='text'
          data-input='description'
          onKeyUp={this.onDescriptionKeyUp}
        />
        <input
          type='text'
          data-input='marcadores'
          onKeyUp={this.onMarcadoresKeyUp}
        />
        <button
          action-trigger='adicionar'
          onClick={this.onAdicionarClick}
        >Add</button>
      </div>
    )
  }
}
