// app/react/src/App.js
import React from 'react'

import '@/App.css'
import api from '@/services/api'
import Tools from '@/components/Tools'
import Form from '@/components/Form'

export default class App extends React.Component {
  constructor (props) {
    super(props)
    this.state = {
      tools: [],
      criterio: '',
      tags: false,
      show: false
    }
  }

  componentDidMount() {
    api.getTools()
      .then(tools => {
        this.setState({ tools })
      })
  }

  onCriterioKeyUp = (e) => {
    this.setState({ criterio: e.target.value })
  }

  onTagsClick = () => {
    const tags = !this.state.tags
    this.setState({ tags })
  }

  onNovaClick = () => {
    this.setState({ show: true })
  }

  onAdicionar = (e) => {
    const tags = (e.marcadores || '').split(' ')
    const tool = { ...e, tags }
    delete tool.marcadores
    api.createTool(tool)
      .then(tool => {
        const before = this.state.tools
        const after = [ ...before, tool ]
        this.setState({ tools: after, show: false })
      })
  }

  onRemover = (tool) => {
    api.removeTool(tool.id)
      .then(() => {
        const before = this.state.tools
        const after = before.filter(t => t.id !== tool.id)
        this.setState({ tools: after })
      })
  }

  render () {
    const criterio = this.state.criterio.trim()
    const tags = this.state.tags
    const tools = this.state.tools
      .filter(tool => {
        return criterio === '' ||
          (!tags && tool.title.includes(criterio)) ||
          (tags && tool.tags.some((tag) => tag.includes(criterio)))
      })
    const show = this.state.show
    return (
      <div className='App'>
        <h1>VUTTR</h1>
        <h3>Very Useful Tools to Remember</h3>
        <input
          type='text'
          data-input='criterio'
          onKeyUp={this.onCriterioKeyUp}
        />
        <input
          type='checkbox'
          data-input='tags'
          onClick={this.onTagsClick}
        />
        <button
          action-trigger='nova'
          onClick={this.onNovaClick}
        >Add</button>
        <Tools tools={tools} onRemover={this.onRemover}/>
        <Form show={show} onAdicionar={this.onAdicionar}/>
      </div>
    )
  }
}

// src/App.vue
<template lang='pug'>
#app
  tool-form(
    v-if='editando',
    :tool='ferramenta',
    @confirmar='adicionar($event)'
  )
  input(
    data-input='criterio',
    :value='criterio',
    @keyup='changeCriterio($event)'
  )
  input(
    type='checkbox',
    data-input='tags',
    :checked='tags',
    @click='toggleTags'
  )
  button(action-trigger='nova', @click='nova') Nova
  tool-line(
		v-for='tool of tools',
		:tool='tool',
		@remover='remover($event)',
		data-set='ferramenta'
  )
</template>

<script>
import api from '@/services/api'
import ToolLine from '@/components/Line'
import ToolForm from '@/components/Form'

export default {
	components: { ToolLine, ToolForm },
  methods: {
    nova () {
      this.ferramenta = {
        title: ''
      }
    },
    toggleTags () {
      this.tags = !this.tags
    },
    changeCriterio (event) {
      this.criterio = event.target.value
    },
    remover (to) {
      api.removeTool(to.id)
        .then(_ => {
          this.ferramentas = this.ferramentas
            .filter(ferramenta => ferramenta.id !== to.id)
        })
    },
    adicionar (ferramenta) {
      const tags = (ferramenta.marcadores || '').split(' ')
      let tool = { ...ferramenta, tags }
      delete tool.marcadores
      api.createTool(tool)
        .then(response => {
          this.ferramentas = [ ...this.ferramentas, { ...response } ]
          this.ferramenta = { empty: true }
        })
    }
  },
  computed: {
    editando () {
      return !this.ferramenta.empty
    },
    tools () {
      const re = new RegExp(this.criterio)
      return this.ferramentas
        .filter(ferramenta => {
          return !this.tags
            ? ferramenta.title.match(re) !== null
            : ferramenta.tags.some(tag => tag.match(re) !== null)
        })
    }
  },
  created () {
    api.getTools()
      .then(response => {
        this.ferramentas = response
      })
  },
  data () {
    return {
      criterio: '',
      tags: false,
      ferramenta: { empty: true },
      ferramentas: []
    }
  }
}
</script>
